"""
Configuración específica de Idealista
"""
from .selectors import (
    LISTADO_ARTICULOS, LISTADO_ID_ATTR, LISTADO_PAGINA,
    FICHA_TITULO, FICHA_UBICACION, FICHA_PRECIO,
    FICHA_STATS_FECHA, FICHA_STATS_LINK, FICHA_BARRIO_MUN,
    FICHA_CARACT_BASIC, FICHA_CARACT_EXTRA, FICHA_MAPA_IMG
)
from .scraping import TEST, PRODUCTION

__all__ = [
    # Selectores
    'LISTADO_ARTICULOS', 'LISTADO_ID_ATTR', 'LISTADO_PAGINA',
    'FICHA_TITULO', 'FICHA_UBICACION', 'FICHA_PRECIO',
    'FICHA_STATS_FECHA', 'FICHA_STATS_LINK', 'FICHA_BARRIO_MUN',
    'FICHA_CARACT_BASIC', 'FICHA_CARACT_EXTRA', 'FICHA_MAPA_IMG',
    # Scraping
    'TEST', 'PRODUCTION'
]